# Generated by Django 2.1.4 on 2018-12-15 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_identity_card', models.CharField(max_length=13)),
                ('cli_name', models.CharField(max_length=50)),
                ('cli_last_name', models.CharField(max_length=50)),
                ('cli_mail', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='create at')),
                ('modify_date', models.DateTimeField(verbose_name='modify at')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='reservation date')),
                ('people_quatity', models.IntegerField(default=1)),
                ('menu_type', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Client')),
            ],
        ),
    ]
