# Generated by Django 2.1.4 on 2018-12-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_client_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cli_mail',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cli_identity_card',
            new_name='identity_card',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cli_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cli_name',
            new_name='name',
        ),
    ]
