# Generated by Django 2.1.4 on 2018-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20181215_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(max_length=50),
        ),
    ]
